### ISSUE TITLE
[bugfixes] AddComponentCommand

### ISSUE THREAD

**Issue by yeekian** [AY2425S1-CS2113-W13-4/tp#114]
- Ensure that the sum of weightage all components is less than or equal to 1.
- Ensure that duplicate components are prevented from being added.

**Comment by RCPilot1604** [comment]
Should point 1 be 100 if we are not shifting to int representation?

**Comment by yeekian** [comment]
We decided to shift to int representation, so the range of weightage for a single component is now [0,100].
