### ISSUE TITLE
[PE-D][Tester B] [Developer Guide] Operation invoked and Return value should be closer to the arrowhead in Sequence Diagram

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-W13-4/tp#145]
In the sequence diagram, currently the operations invoked and return values are at the center of the arrows. It would be easier for users if they are closer to the arrowhead such that users are able to identify each operation invoked or return value to the arrow quickly. 

![image.png](https://raw.githubusercontent.com/glenda-1506/ped/main/files/16bb0d7e-9fdd-4b83-9a17-ddf06bbafffc.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: glenda-1506/ped#2

**Comment by yeekian** [comment]
The issue will not be fixed as the phrases above the arrows are still clear and easy to read. Issue will be closed.
